apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: cbdmock
spec:
  selector:
    cbdmock-service: stage
  externalIPs: []
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: []
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stage
  labels:
    cbdmock-cluster: stage
  namespace: cbdmock
spec:
  replicas: 1
  selector:
    matchLabels:
      cbdmock-cluster: stage
  template:
    metadata:
      labels:
        cbdmock-cluster: stage
        cbdmock-service: stage
    spec:
      containers:
      - image: gcr.io/stevenkim-cbd-mock/cbdmock
        name: cbdmock-stage
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m

